#!/bin/sh

target=${1:-'/home/hs'}
rundir="/root"

(cd ../src && make clean && make uninstall && make && make install && make clean)
mkfile="./makefile"
exe=$(awk '/^EXECUTABLE/{print $NF}' ./makefile);

make clean && make
mv -f ./$exe $rundir/
make clean

curr=$(pwd);
cd $rundir;
rm -rf gmon.out;
${rundir}/${exe} $target;
if grep ^LINKFLAGS ${curr}/${mkfile} | grep -qs '\-pg'; then
  gprof -b ${rundir}/${exe} gmon.out | less
fi;
cd $curr

