#!/bin/sh

mkfile="./makefile"
exe=$(awk '/^EXECUTABLE/{print $NF}' ./makefile);

make clean
make
rm -rf *o *.d gmon.out
./$exe $1; 

if grep ^LINKFLAGS $mkfile | grep -qs '\-pg'; then
  gprof -b ./$exe gmon.out | less
fi
